generic-service:
  nameOverride: hmpps-appointment-reminders-ui
  serviceAccountName: hmpps-appointment-reminders-ui
  productId: HMPPS518

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-appointment-reminders-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-appointment-reminders-ui-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: 'production'
    REDIS_ENABLED: 'true'
    REDIS_TLS_ENABLED: 'true'
    TOKEN_VERIFICATION_ENABLED: 'true'
    AUDIT_SQS_REGION: 'eu-west-2'
    AUDIT_SERVICE_NAME: 'hmpps-appointment-reminders-ui'
    AUDIT_ENABLED: 'true'

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  namespace_secrets:
    hmpps-auth:
      AUTH_CODE_CLIENT_ID: 'AUTH_CODE_CLIENT_ID'
      AUTH_CODE_CLIENT_SECRET: 'AUTH_CODE_CLIENT_SECRET'
      CLIENT_CREDS_CLIENT_ID: 'CLIENT_CREDS_CLIENT_ID'
      CLIENT_CREDS_CLIENT_SECRET: 'CLIENT_CREDS_CLIENT_SECRET'
    govuk-notify:
      NOTIFY_N56_API_KEY: 'N56_API_KEY'
      NOTIFY_N50_API_KEY: 'N50_API_KEY'
      NOTIFY_N07_API_KEY: 'N07_API_KEY'
      NOTIFY_N03_API_KEY: 'N03_API_KEY'
      NOTIFY_N52_API_KEY: 'N52_API_KEY'
    elasticache-redis:
      SESSION_SECRET: 'session_secret'
      REDIS_HOST: 'primary_endpoint_address'
      REDIS_AUTH_TOKEN: 'auth_token'
    application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: 'sqs_queue_url'

  allowlist:
    groups:
      - digital_staff_and_mojo
      - unilink_staff
      - probation

generic-prometheus-alerts:
  targetApplication: hmpps-appointment-reminders-ui
