---
# Per environment values which override defaults in hmpps-appointment-reminders-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: appointment-reminders-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://appointment-reminders-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    DELIUS_INTEGRATION_API_URL: "https://appointment-reminders-and-delius-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV

generic-prometheus-alerts:
  alertSeverity: probation-integration-notifications
