name: Security npm dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * MON-FRI" # Every weekday at 05:30 UTC
jobs:
  security-npm-dependency-check:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security npm dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_npm_dependency.yml@8de783c7b6dc61ad8ba384924dc1fe93098d9995 # v2.13.1
    with:
      channel_id: probation-integration-notifications
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
