name: Security trivy dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * MON-FRI" # Every weekday at 05:30 UTC
jobs:
  security-typescript-trivy-check:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@255709aa1349e6ec1d77b3fec0ed6cbe9f962973 # v2.14.1
    with:
      channel_id: probation-integration-notifications
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
