name: Security npm dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * MON-FRI" # Every weekday at 05:30 UTC
jobs:
  security-npm-dependency-check:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security npm dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_npm_dependency.yml@607c82f9fa98d1c35286644d7d70f13c50c4316b # v2.13.2
    with:
      channel_id: probation-integration-notifications
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
